use wasm_bindgen::prelude::*;
use wasm_refgen::wasm_refgen;

#[derive(Clone)]
#[wasm_bindgen(js_name = Foo)]
pub struct WasmFoo {
    _value: u32,
}

#[wasm_refgen(js_ref = JsFoo)]
#[wasm_bindgen(js_class = "Foo")]
impl WasmFoo {
    #[wasm_bindgen(constructor)]
    pub fn new(value: u32) -> Self {
        Self { _value: value }
    }
}

/// The macro generates a `JsFoo` extern type. Verify it exists and
/// implements `JsCast` (which `wasm-bindgen` derives for extern types).
#[test]
fn generated_js_ref_type_implements_js_cast() {
    fn assert_js_cast<T: JsCast>() {}
    assert_js_cast::<JsFoo>();
}

/// The macro generates `FromJsRef for WasmFoo` with `JsRef = JsFoo`.
#[test]
fn generated_from_js_ref_impl() {
    fn assert_from_js_ref<T: from_js_ref::FromJsRef>() {}
    assert_from_js_ref::<WasmFoo>();
}

/// `From<&JsFoo> for WasmFoo` is generated by the macro.
#[test]
fn generated_from_js_ref_for_type() {
    fn assert_from<T, U: From<T>>() {}
    assert_from::<&JsFoo, WasmFoo>();
}

/// `From<WasmFoo> for JsFoo` is generated by the macro.
#[test]
fn generated_from_type_for_js_ref() {
    fn assert_from<T, U: From<T>>() {}
    assert_from::<WasmFoo, JsFoo>();
}

/// `JsDeref<WasmFoo>` is blanket-implemented for `JsFoo` via `FromJsRef`.
#[test]
fn generated_js_deref_impl() {
    fn assert_js_deref<T: from_js_ref::JsDeref<WasmFoo>>() {}
    assert_js_deref::<JsFoo>();
}

/// Verify the `JsFoo` extern type targets the correct JS class name (`Foo`,
/// not `JsFoo`). Without `js_name = Foo` on the extern type declaration,
/// `wasm-bindgen` would default to `JsFoo` as the JS class name, causing
/// `instanceof` to fail at runtime.
///
/// We verify this indirectly: the generated `JsFoo` type satisfies
/// `JsCast + AsRef<JsValue>`, meaning the extern type is properly wired to
/// a JS class. The fact that `JsFoo: JsCast` compiles with `js_name = Foo`
/// confirms the binding exists. A direct `instanceof` runtime test would
/// require a Wasm environment.
///
/// This test exercises the fix from 2026-03-14 where `js_name` was added to
/// the extern block's type declaration.
#[test]
fn js_ref_type_is_js_cast_compatible() {
    // Compile-time proof that JsFoo can be used in dyn_ref/dyn_into call sites.
    fn assert_castable<T: JsCast + AsRef<JsValue>>() {}
    assert_castable::<JsFoo>();
}

// Repeat with a different naming convention to ensure the macro handles
// the js_class → js_name mapping correctly for various identifiers.

#[derive(Clone)]
#[wasm_bindgen(js_name = CommitWithBlob)]
pub struct WasmCommitWithBlob {
    _data: u32,
}

#[wasm_refgen(js_ref = JsCommitWithBlob)]
#[wasm_bindgen(js_class = "CommitWithBlob")]
impl WasmCommitWithBlob {
    #[wasm_bindgen(constructor)]
    pub fn new(data: u32) -> Self {
        Self { _data: data }
    }
}

#[test]
fn multi_word_class_name_generates_correct_types() {
    fn assert_js_cast<T: JsCast>() {}
    fn assert_from_js_ref<T: from_js_ref::FromJsRef>() {}

    assert_js_cast::<JsCommitWithBlob>();
    assert_from_js_ref::<WasmCommitWithBlob>();
}

#[test]
fn multi_word_class_is_js_cast_compatible() {
    fn assert_castable<T: JsCast + AsRef<JsValue>>() {}
    assert_castable::<JsCommitWithBlob>();
}
