//! Implementation of the `#[wasm_implements(TraitName)]` attribute macro.
//!
//! Placed on a `#[wasm_bindgen]` impl block, generates:
//! 1. A runtime tag method (`__wasm_impl_{TraitName}`) injected into the impl block
//! 2. A hidden `const _: () = { impl Trait for Type { ... } }` witness
//!    for compile-time signature checking

use alloc::{
    string::{String, ToString},
    vec::Vec,
};
use proc_macro2::TokenStream;
use quote::quote;
use syn::{spanned::Spanned, ImplItem, ImplItemFn, ItemImpl, Path};

use crate::shared::{
    attrs::{extract_js_name_from_attrs, strip_wasm_bindgen},
    method::{arg_names, has_self_receiver, is_pub, to_rpitit_signature},
    naming::{tag_method_js_name, tag_method_rust_ident},
};

/// Core implementation of `#[wasm_implements]`.
pub(crate) fn wasm_implements_impl(trait_path: &Path, mut impl_block: ItemImpl) -> TokenStream {
    // Reject trait impls — we need an inherent impl
    if let Some((_, path, _)) = &impl_block.trait_ {
        return syn::Error::new(
            path.span(),
            "#[wasm_implements] must be used on an inherent impl, not a trait impl",
        )
        .to_compile_error();
    }

    let self_ty = &impl_block.self_ty;

    // Extract the last segment of the trait path for naming
    let trait_name = match trait_path.segments.last() {
        Some(seg) => &seg.ident,
        None => {
            return syn::Error::new(
                trait_path.span(),
                "#[wasm_implements] requires a trait path",
            )
            .to_compile_error();
        }
    };

    // Collect all pub fn items from the impl block
    let pub_methods: Vec<&ImplItemFn> = impl_block
        .items
        .iter()
        .filter_map(|item| match item {
            ImplItem::Fn(method) if is_pub(method) => Some(method),
            ImplItem::Const(_)
            | ImplItem::Fn(_)
            | ImplItem::Type(_)
            | ImplItem::Macro(_)
            | ImplItem::Verbatim(_)
            | _ => None,
        })
        .collect();

    // Generate the witness methods
    let witness_methods: Vec<TokenStream> = pub_methods
        .iter()
        .map(|method| {
            let sig = &method.sig;
            let method_name = &sig.ident;

            // Transform to RPITIT if async
            let witness_sig = to_rpitit_signature(sig);

            // Strip wasm_bindgen attrs
            let clean_attrs = strip_wasm_bindgen(&method.attrs);

            let arg_names: Vec<_> = arg_names(sig);

            let body: TokenStream = if has_self_receiver(sig) {
                quote! { #self_ty::#method_name(self, #(#arg_names),*) }
            } else {
                quote! { #self_ty::#method_name(#(#arg_names),*) }
            };

            quote! {
                #(#clean_attrs)*
                #witness_sig {
                    #body
                }
            }
        })
        .collect();

    // Extract JS names from pub methods BEFORE injecting the tag method
    // (to avoid borrow conflict with impl_block.items).
    let actual_js_names: Vec<String> = pub_methods
        .iter()
        .map(|method| {
            extract_js_name_from_attrs(&method.attrs)
                .unwrap_or_else(|| method.sig.ident.to_string())
        })
        .collect();

    // Drop the borrow on pub_methods so we can mutate impl_block
    drop(pub_methods);

    // Generate the runtime tag method
    let tag_rust_name = tag_method_rust_ident(trait_name);
    let tag_js_name = tag_method_js_name(trait_name);

    // Check for collision with existing methods before injecting
    let has_collision = impl_block.items.iter().any(|item| {
        if let ImplItem::Fn(method) = item {
            method.sig.ident == tag_rust_name
        } else {
            false
        }
    });

    if has_collision {
        return syn::Error::new(
            trait_name.span(),
            alloc::format!(
                "impl block already contains a method named `{tag_rust_name}`, \
                 which conflicts with the tag method generated by #[wasm_implements]"
            ),
        )
        .to_compile_error();
    }

    let tag_method: syn::ImplItemFn = syn::parse_quote! {
        #[::wasm_bindgen::prelude::wasm_bindgen(js_name = #tag_js_name)]
        pub fn #tag_rust_name(&self) -> bool {
            true
        }
    };

    // Inject tag method into the original impl block
    impl_block.items.push(ImplItem::Fn(tag_method));

    let witness_and_check =
        gen_witness_and_check(trait_path, self_ty, &witness_methods, &actual_js_names);

    quote! {
        #impl_block
        #witness_and_check
    }
}

/// Generate the hidden witness `impl Trait for Type` and the compile-time
/// JS method name check, in a single `const _: ()` block.
fn gen_witness_and_check(
    trait_path: &Path,
    self_ty: &syn::Type,
    witness_methods: &[TokenStream],
    actual_js_names: &[String],
) -> TokenStream {
    let actual_literals: Vec<TokenStream> = actual_js_names.iter().map(|s| quote!(#s)).collect();

    quote! {
        const _: () = {
            impl #trait_path for #self_ty {
                #(#witness_methods)*
            }

            const __ACTUAL: &[&str] = &[#(#actual_literals),*];
            const __EXPECTED: &[&str] = <#self_ty as #trait_path>::__JS_INTERFACE;

            const fn __wasm_trait_str_eq(a: &str, b: &str) -> bool {
                let a = a.as_bytes();
                let b = b.as_bytes();
                if a.len() != b.len() { return false; }
                let mut i = 0;
                while i < a.len() {
                    if a[i] != b[i] { return false; }
                    i += 1;
                }
                true
            }

            const fn __wasm_trait_contains(haystack: &[&str], needle: &str) -> bool {
                let mut i = 0;
                while i < haystack.len() {
                    if __wasm_trait_str_eq(haystack[i], needle) { return true; }
                    i += 1;
                }
                false
            }

            const fn __wasm_trait_check(expected: &[&str], actual: &[&str]) -> bool {
                let mut i = 0;
                while i < expected.len() {
                    if !__wasm_trait_contains(actual, expected[i]) { return false; }
                    i += 1;
                }
                true
            }

            const { assert!(
                __wasm_trait_check(__EXPECTED, __ACTUAL),
                "impl block is missing one or more JS methods required by the interface (check js_name attrs)"
            ); }
        };
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::{
        boxed::Box,
        string::{String, ToString},
    };
    use quote::quote;

    type TestResult = Result<(), Box<dyn core::error::Error>>;

    fn expand(
        attr: proc_macro2::TokenStream,
        item: proc_macro2::TokenStream,
    ) -> Result<String, syn::Error> {
        let trait_path: Path = syn::parse2(attr)?;
        let impl_block: ItemImpl = syn::parse2(item)?;
        Ok(wasm_implements_impl(&trait_path, impl_block).to_string())
    }

    #[test]
    fn generates_tag_method() -> TestResult {
        let output = expand(
            quote!(Transport),
            quote! {
                impl WasmFoo {
                    pub fn js_put(&self, value: u32) -> u32 { value }
                }
            },
        )?;

        assert!(output.contains("__wasm_impl_transport"));
        assert!(output.contains("__wasm_impl_Transport"));
        Ok(())
    }

    #[test]
    fn generates_witness_impl() -> TestResult {
        let output = expand(
            quote!(Transport),
            quote! {
                impl WasmFoo {
                    pub fn js_put(&self, value: u32) -> u32 { value }
                }
            },
        )?;

        assert!(output.contains("impl Transport for WasmFoo"));
        assert!(output.contains("const _ : () ="));
        Ok(())
    }

    #[test]
    fn witness_delegates_to_inherent_method() -> TestResult {
        let output = expand(
            quote!(Transport),
            quote! {
                impl WasmFoo {
                    pub fn js_put(&self, value: u32) -> u32 { value }
                }
            },
        )?;

        assert!(
            output.contains("WasmFoo :: js_put (self , value)")
                || output.contains("WasmFoo :: js_put(self, value)")
                || output.contains("WasmFoo::js_put(self, value)"),
        );
        Ok(())
    }

    #[test]
    fn strips_wasm_bindgen_attrs_from_witness() -> TestResult {
        let output = expand(
            quote!(Transport),
            quote! {
                impl WasmFoo {
                    #[wasm_bindgen(js_name = "put")]
                    pub fn js_put(&self, value: u32) -> u32 { value }
                }
            },
        )?;

        let witness_section = output
            .split_once("const _ : () =")
            .ok_or("must have witness")?
            .1;
        assert!(!witness_section.contains("wasm_bindgen"));
        Ok(())
    }

    #[test]
    fn async_method_becomes_rpitit_in_witness() -> TestResult {
        let output = expand(
            quote!(Transport),
            quote! {
                impl WasmFoo {
                    pub async fn js_send(&self, data: u32) -> u32 { data }
                }
            },
        )?;

        let witness_section = output
            .split_once("const _ : () =")
            .ok_or("must have witness")?
            .1;
        assert!(witness_section.contains("Future"));
        assert!(!witness_section.contains("async"));
        Ok(())
    }

    #[test]
    fn preserves_original_impl_block() -> TestResult {
        let output = expand(
            quote!(Transport),
            quote! {
                impl WasmFoo {
                    #[wasm_bindgen(js_name = "put")]
                    pub fn js_put(&self, value: u32) -> u32 { value }
                }
            },
        )?;

        let impl_pos = output
            .find("impl WasmFoo")
            .ok_or("must have original impl")?;
        let witness_pos = output.find("const _ : () =").ok_or("must have witness")?;
        assert!(impl_pos < witness_pos);
        Ok(())
    }

    #[test]
    fn static_method_delegates_without_self() -> TestResult {
        let output = expand(
            quote!(Factory),
            quote! {
                impl WasmFoo {
                    pub fn js_create(name: u32) -> u32 { name }
                }
            },
        )?;

        let witness_section = output
            .split_once("const _ : () =")
            .ok_or("must have witness")?
            .1;
        assert!(
            witness_section.contains("WasmFoo :: js_create (name)")
                || witness_section.contains("WasmFoo :: js_create(name)")
                || witness_section.contains("WasmFoo::js_create(name)"),
        );
        Ok(())
    }

    #[test]
    fn supports_module_path_trait() -> TestResult {
        let output = expand(
            quote!(my_module::Transport),
            quote! {
                impl WasmFoo {
                    pub fn js_put(&self, value: u32) -> u32 { value }
                }
            },
        )?;

        assert!(
            output.contains("impl my_module :: Transport for WasmFoo")
                || output.contains("impl my_module::Transport for WasmFoo"),
        );
        assert!(output.contains("__wasm_impl_transport"));
        Ok(())
    }

    #[test]
    fn error_on_trait_impl() -> TestResult {
        let output = expand(
            quote!(Transport),
            quote! {
                impl SomeTrait for WasmFoo {
                    fn js_put(&self) {}
                }
            },
        )?;

        assert!(output.contains("compile_error"));
        Ok(())
    }

    #[test]
    fn ignores_private_methods() -> TestResult {
        let output = expand(
            quote!(Transport),
            quote! {
                impl WasmFoo {
                    pub fn js_put(&self, value: u32) -> u32 { value }
                    fn private_helper(&self) -> u32 { 42 }
                }
            },
        )?;

        let witness_section = output
            .split_once("const _ : () =")
            .ok_or("must have witness")?
            .1;
        assert!(!witness_section.contains("private_helper"));
        assert!(witness_section.contains("js_put"));
        Ok(())
    }

    #[test]
    fn generates_js_name_check() -> TestResult {
        let output = expand(
            quote!(Transport),
            quote! {
                impl WasmFoo {
                    #[wasm_bindgen(js_name = "sendBytes")]
                    pub fn js_send_bytes(&self, value: u32) -> u32 { value }
                }
            },
        )?;

        assert!(output.contains("__JS_INTERFACE"));
        assert!(output.contains("sendBytes"));
        Ok(())
    }

    #[test]
    fn js_name_check_includes_all_methods() -> TestResult {
        let output = expand(
            quote!(Storage),
            quote! {
                impl WasmFoo {
                    #[wasm_bindgen(js_name = "save")]
                    pub fn js_save(&self, value: u32) { }

                    #[wasm_bindgen(js_name = "load")]
                    pub fn js_load(&self, key: u32) -> u32 { key }

                    #[wasm_bindgen(js_name = "delete")]
                    pub fn js_delete(&self, key: u32) -> bool { true }
                }
            },
        )?;

        assert!(output.contains(r#""save""#));
        assert!(output.contains(r#""load""#));
        assert!(output.contains(r#""delete""#));
        Ok(())
    }

    #[test]
    fn js_name_check_uses_rust_name_when_no_js_name() -> TestResult {
        let output = expand(
            quote!(Transport),
            quote! {
                impl WasmFoo {
                    pub fn js_send_bytes(&self, value: u32) -> u32 { value }
                }
            },
        )?;

        assert!(output.contains(r#""js_send_bytes""#));
        Ok(())
    }

    #[test]
    fn js_name_check_contains_const_assertion() -> TestResult {
        let output = expand(
            quote!(Transport),
            quote! {
                impl WasmFoo {
                    #[wasm_bindgen(js_name = "send")]
                    pub fn js_send(&self) {}
                }
            },
        )?;

        assert!(output.contains("__wasm_trait_check"));
        assert!(output.contains("assert !"));
        Ok(())
    }
}
