name: Test Default Features on Host

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Test workspace
      run: cargo test --workspace --verbose

    - name: Test workspace (all features)
      run: cargo test --workspace --all-features --verbose

    - name: Run Doc Tests
      run: cargo test --doc --workspace

  test-nix:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v21

    - name: Setup Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@v13

    - name: Test via Nix
      run: nix develop --command cargo test --workspace --verbose
